/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DashboardKasir;

import raven.glasspanepopup.GlassPanePopup;


/**
 *
 * @author Lenovo
 */
public class DashboardKasir extends javax.swing.JFrame {

    /**
     * Creates new form DashboardAdmin
     */
    public DashboardKasir() {
        initComponents();
        GlassPanePopup.install(this);
        round2.setVisible(false);
        round3.setVisible(false);
        round4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnroundkotak20 = new Swing.btnroundkotak1();
        btnroundkotak21 = new Swing.btnroundkotak1();
        btnroundkotak22 = new Swing.btnroundkotak1();
        btnroundkotak19 = new Swing.btnroundkotak1();
        btnroundkotak15 = new Swing.btnroundkotak1();
        btnroundkotak16 = new Swing.btnroundkotak1();
        btnroundkotak18 = new Swing.btnroundkotak1();
        btnroundkotak17 = new Swing.btnroundkotak1();
        btnroundkotak14 = new Swing.btnroundkotak1();
        btnroundkotak13 = new Swing.btnroundkotak1();
        btnroundkotak12 = new Swing.btnroundkotak1();
        btnroundkotak11 = new Swing.btnroundkotak1();
        btnroundkotak3 = new Swing.btnroundkotak();
        btnroundkotak2 = new Swing.btnroundkotak();
        btnroundkotak1 = new Swing.btnroundkotak();
        jButton2 = new javax.swing.JButton();
        nama = new javax.swing.JLabel();
        round4 = new Swing.round();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        round3 = new Swing.round();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        round2 = new Swing.round();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnroundkotak20.setBackground(new java.awt.Color(217, 217, 217));
        btnroundkotak20.setEnabled(false);
        getContentPane().add(btnroundkotak20, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 740, 160, 160));

        btnroundkotak21.setBackground(new java.awt.Color(241, 241, 241));
        getContentPane().add(btnroundkotak21, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 720, 460, 200));

        btnroundkotak22.setBackground(new java.awt.Color(217, 217, 217));
        btnroundkotak22.setEnabled(false);
        btnroundkotak22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnroundkotak22ActionPerformed(evt);
            }
        });
        getContentPane().add(btnroundkotak22, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 740, 160, 160));

        btnroundkotak19.setBackground(new java.awt.Color(241, 241, 241));
        getContentPane().add(btnroundkotak19, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 720, 460, 200));

        btnroundkotak15.setBackground(new java.awt.Color(217, 217, 217));
        btnroundkotak15.setEnabled(false);
        btnroundkotak15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnroundkotak15ActionPerformed(evt);
            }
        });
        getContentPane().add(btnroundkotak15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 530, 160, 160));

        btnroundkotak16.setBackground(new java.awt.Color(241, 241, 241));
        btnroundkotak16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnroundkotak16ActionPerformed(evt);
            }
        });
        getContentPane().add(btnroundkotak16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 460, 200));

        btnroundkotak18.setBackground(new java.awt.Color(217, 217, 217));
        btnroundkotak18.setEnabled(false);
        getContentPane().add(btnroundkotak18, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 530, 160, 160));

        btnroundkotak17.setBackground(new java.awt.Color(241, 241, 241));
        getContentPane().add(btnroundkotak17, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 510, 460, 200));

        btnroundkotak14.setBackground(new java.awt.Color(217, 217, 217));
        btnroundkotak14.setEnabled(false);
        getContentPane().add(btnroundkotak14, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 160, 160));

        btnroundkotak13.setBackground(new java.awt.Color(241, 241, 241));
        btnroundkotak13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnroundkotak13ActionPerformed(evt);
            }
        });
        getContentPane().add(btnroundkotak13, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, 460, 200));

        btnroundkotak12.setBackground(new java.awt.Color(217, 217, 217));
        btnroundkotak12.setEnabled(false);
        btnroundkotak12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnroundkotak12ActionPerformed(evt);
            }
        });
        getContentPane().add(btnroundkotak12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 160, 160));

        btnroundkotak11.setBackground(new java.awt.Color(241, 241, 241));
        btnroundkotak11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnroundkotak11ActionPerformed(evt);
            }
        });
        getContentPane().add(btnroundkotak11, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 300, 460, 200));

        btnroundkotak3.setBackground(new java.awt.Color(173, 243, 155));
        btnroundkotak3.setForeground(new java.awt.Color(102, 102, 102));
        btnroundkotak3.setText("Bayar Nanti");
        btnroundkotak3.setFont(new java.awt.Font("Futura Md BT", 1, 30)); // NOI18N
        getContentPane().add(btnroundkotak3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1466, 880, 294, 96));

        btnroundkotak2.setBackground(new java.awt.Color(204, 255, 255));
        btnroundkotak2.setForeground(new java.awt.Color(102, 102, 102));
        btnroundkotak2.setText("Cancel");
        btnroundkotak2.setFont(new java.awt.Font("Futura Md BT", 1, 30)); // NOI18N
        btnroundkotak2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnroundkotak2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnroundkotak2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1168, 880, 288, 96));

        btnroundkotak1.setBackground(new java.awt.Color(62, 181, 84));
        btnroundkotak1.setForeground(new java.awt.Color(255, 255, 255));
        btnroundkotak1.setText("Bayar Sekarang");
        btnroundkotak1.setFont(new java.awt.Font("Futura Md BT", 1, 36)); // NOI18N
        btnroundkotak1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnroundkotak1MouseEntered(evt);
            }
        });
        btnroundkotak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnroundkotak1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnroundkotak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1166, 705, 601, 95));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Komponen/titik 3.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1810, 40, -1, -1));

        nama.setFont(new java.awt.Font("Futura Md BT", 1, 24)); // NOI18N
        nama.setForeground(new java.awt.Color(255, 255, 255));
        nama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Komponen/Ellipse 6.png"))); // NOI18N
        nama.setIconTextGap(20);
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 25, 260, 50));

        round4.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane3.setFont(new java.awt.Font("Futura Md BT", 1, 24)); // NOI18N

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Futura Md BT", 1, 21)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(102, 102, 102));
        jTextArea3.setRows(5);
        jTextArea3.setText("Nama\nProduk");
        jScrollPane3.setViewportView(jTextArea3);

        jTextField7.setBackground(new java.awt.Color(204, 255, 255));
        jTextField7.setFont(new java.awt.Font("Futura Md BT", 1, 21)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(102, 102, 102));
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("1");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Futura Md BT", 1, 26)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(102, 102, 102));
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField8.setText("15.000");
        jTextField8.setAutoscrolls(false);
        jTextField8.setBorder(null);
        jTextField8.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Futura Md BT", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Rupiah");
        jLabel7.setIconTextGap(20);

        jTextField9.setBackground(new java.awt.Color(204, 255, 255));
        jTextField9.setFont(new java.awt.Font("Futura Md BT", 1, 21)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(102, 102, 102));
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setBorder(null);
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout round4Layout = new javax.swing.GroupLayout(round4);
        round4.setLayout(round4Layout);
        round4Layout.setHorizontalGroup(
            round4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(round4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(round4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jTextField9)
        );
        round4Layout.setVerticalGroup(
            round4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(round4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(round4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(round4Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        getContentPane().add(round4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 480, 560, -1));

        round3.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setFont(new java.awt.Font("Futura Md BT", 1, 24)); // NOI18N

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Futura Md BT", 1, 21)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(102, 102, 102));
        jTextArea2.setRows(5);
        jTextArea2.setText("Nama\nProduk");
        jScrollPane2.setViewportView(jTextArea2);

        jTextField4.setBackground(new java.awt.Color(204, 255, 255));
        jTextField4.setFont(new java.awt.Font("Futura Md BT", 1, 21)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(102, 102, 102));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("1");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Futura Md BT", 1, 26)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(102, 102, 102));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField5.setText("15.000");
        jTextField5.setAutoscrolls(false);
        jTextField5.setBorder(null);
        jTextField5.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Futura Md BT", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Rupiah");
        jLabel6.setIconTextGap(20);

        jTextField6.setBackground(new java.awt.Color(204, 255, 255));
        jTextField6.setFont(new java.awt.Font("Futura Md BT", 1, 21)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(102, 102, 102));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setBorder(null);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout round3Layout = new javax.swing.GroupLayout(round3);
        round3.setLayout(round3Layout);
        round3Layout.setHorizontalGroup(
            round3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(round3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(round3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jTextField6)
        );
        round3Layout.setVerticalGroup(
            round3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(round3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(round3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(round3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        getContentPane().add(round3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 380, 560, -1));

        round2.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setFont(new java.awt.Font("Futura Md BT", 1, 24)); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Futura Md BT", 1, 21)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(102, 102, 102));
        jTextArea1.setRows(5);
        jTextArea1.setText("Nama\nProduk");
        jScrollPane1.setViewportView(jTextArea1);

        jTextField1.setBackground(new java.awt.Color(204, 255, 255));
        jTextField1.setFont(new java.awt.Font("Futura Md BT", 1, 21)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(102, 102, 102));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Futura Md BT", 1, 26)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(102, 102, 102));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.setText("15.000");
        jTextField2.setAutoscrolls(false);
        jTextField2.setBorder(null);
        jTextField2.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Futura Md BT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Rupiah");
        jLabel5.setIconTextGap(20);

        jTextField3.setBackground(new java.awt.Color(204, 255, 255));
        jTextField3.setFont(new java.awt.Font("Futura Md BT", 1, 21)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(102, 102, 102));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setBorder(null);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout round2Layout = new javax.swing.GroupLayout(round2);
        round2.setLayout(round2Layout);
        round2Layout.setHorizontalGroup(
            round2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(round2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(round2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jTextField3)
        );
        round2Layout.setVerticalGroup(
            round2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(round2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(round2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(round2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        getContentPane().add(round2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 280, 560, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Komponen/kasir.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnroundkotak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnroundkotak1ActionPerformed
        GlassPanePopup.showPopup(new pay());
    }//GEN-LAST:event_btnroundkotak1ActionPerformed

    private void btnroundkotak1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnroundkotak1MouseEntered
        
    }//GEN-LAST:event_btnroundkotak1MouseEntered

    private void btnroundkotak15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnroundkotak15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnroundkotak15ActionPerformed

    private void btnroundkotak22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnroundkotak22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnroundkotak22ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnroundkotak12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnroundkotak12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnroundkotak12ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void btnroundkotak2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnroundkotak2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnroundkotak2ActionPerformed

    private void btnroundkotak11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnroundkotak11ActionPerformed
        round2.setVisible(true);
    }//GEN-LAST:event_btnroundkotak11ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void btnroundkotak13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnroundkotak13ActionPerformed
        round3.setVisible(true);
    }//GEN-LAST:event_btnroundkotak13ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void btnroundkotak16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnroundkotak16ActionPerformed
        round4.setVisible(true);
    }//GEN-LAST:event_btnroundkotak16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardKasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Swing.btnroundkotak btnroundkotak1;
    private Swing.btnroundkotak1 btnroundkotak11;
    private Swing.btnroundkotak1 btnroundkotak12;
    private Swing.btnroundkotak1 btnroundkotak13;
    private Swing.btnroundkotak1 btnroundkotak14;
    private Swing.btnroundkotak1 btnroundkotak15;
    private Swing.btnroundkotak1 btnroundkotak16;
    private Swing.btnroundkotak1 btnroundkotak17;
    private Swing.btnroundkotak1 btnroundkotak18;
    private Swing.btnroundkotak1 btnroundkotak19;
    private Swing.btnroundkotak btnroundkotak2;
    private Swing.btnroundkotak1 btnroundkotak20;
    private Swing.btnroundkotak1 btnroundkotak21;
    private Swing.btnroundkotak1 btnroundkotak22;
    private Swing.btnroundkotak btnroundkotak3;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    public javax.swing.JLabel nama;
    private Swing.round round2;
    private Swing.round round3;
    private Swing.round round4;
    // End of variables declaration//GEN-END:variables
}
