/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DashboardKasir;

/**
 *
 * @author Lenovo
 */
public class produk extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public produk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnroundkotak2 = new Swing.btnroundkotak();
        btnroundkotak1 = new Swing.btnroundkotak();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnroundkotak2.setBackground(new java.awt.Color(204, 204, 204));
        add(btnroundkotak2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 160, 160));

        btnroundkotak1.setBackground(new java.awt.Color(204, 255, 255));
        btnroundkotak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnroundkotak1ActionPerformed(evt);
            }
        });
        add(btnroundkotak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 200));
    }// </editor-fold>//GEN-END:initComponents

    private void btnroundkotak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnroundkotak1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnroundkotak1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Swing.btnroundkotak btnroundkotak1;
    private Swing.btnroundkotak btnroundkotak2;
    // End of variables declaration//GEN-END:variables
}
