/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DashboardKasir;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import raven.glasspanepopup.GlassPanePopup;

/**
 *
 * @author Lenovo
 */
public class tamduk extends javax.swing.JPanel {

    /**
     * Creates new form tamduk
     */
    public tamduk() {
        initComponents();
        setOpaque(false);
        kosong();
        
    }
    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fill(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 15, 15));
        g2.dispose();
        super.paintComponent(grphcs);
    }
    public void kosong(){
        nm_produk.setText("");
        hrg_produk.setText("");
        kd_produk.setText("");
        stok_produk.setText("");
        tgl_exp.setText("");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stok_produk = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tgl_exp = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        hrg_produk = new javax.swing.JTextField();
        nm_produk = new javax.swing.JTextField();
        kd_produk = new javax.swing.JTextField();
        btnroundkotak2 = new Swing.btnroundkotak();
        btnroundkotak1 = new Swing.btnroundkotak();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1120, 731));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(stok_produk, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, 730, 50));

        jLabel6.setFont(new java.awt.Font("Futura Md BT", 1, 18)); // NOI18N
        jLabel6.setText("Stok");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, -1, -1));
        add(tgl_exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 730, 50));

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("Tambah Gmbar");
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 190, 190));
        add(hrg_produk, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 730, 50));
        add(nm_produk, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 730, 50));
        add(kd_produk, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 730, 50));

        btnroundkotak2.setText("Cancel");
        btnroundkotak2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnroundkotak2ActionPerformed(evt);
            }
        });
        add(btnroundkotak2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 20, 100, 30));

        btnroundkotak1.setText("Simpan");
        btnroundkotak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnroundkotak1ActionPerformed(evt);
            }
        });
        add(btnroundkotak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 620, 200, 60));

        jLabel1.setFont(new java.awt.Font("Futura Md BT", 1, 18)); // NOI18N
        jLabel1.setText("Harga Produk");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, -1, -1));

        jLabel2.setFont(new java.awt.Font("Futura Md BT", 1, 18)); // NOI18N
        jLabel2.setText("Input Data Produk Baru");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Futura Md BT", 1, 18)); // NOI18N
        jLabel3.setText("Kode Produk");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Futura Md BT", 1, 18)); // NOI18N
        jLabel4.setText("Nama Produk");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Futura Md BT", 1, 18)); // NOI18N
        jLabel5.setText("Tanggal Kadaluwarsa");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnroundkotak2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnroundkotak2ActionPerformed
        GlassPanePopup.closePopupLast();
        DashboardAdmin dashmin = new DashboardAdmin();
        dashmin.tampil_table();
    }//GEN-LAST:event_btnroundkotak2ActionPerformed

    private void btnroundkotak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnroundkotak1ActionPerformed
        try {
            String sql = "INSERT INTO produk (id_produk, nama_produk, harga_produk, stok, tgl_exp) VALUES ('"+kd_produk.getText()+"', '"+nm_produk.getText()+"', '"+hrg_produk.getText()+"','"+stok_produk.getText()+"', '"+tgl_exp.getText()+"')";
            java.sql.Connection conn=(Connection)Koneksi.konek.configDBek();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data gagal ditambahkan"+ e.getMessage());
        }
        
    }//GEN-LAST:event_btnroundkotak1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Swing.btnroundkotak btnroundkotak1;
    private Swing.btnroundkotak btnroundkotak2;
    private javax.swing.JTextField hrg_produk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField kd_produk;
    private javax.swing.JTextField nm_produk;
    private javax.swing.JTextField stok_produk;
    private javax.swing.JTextField tgl_exp;
    // End of variables declaration//GEN-END:variables
}
