/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import Koneksi.konek;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import javax.swing.JOptionPane;
import raven.glasspanepopup.GlassPanePopup;

/**
 *
 * @author Lenovo
 */
public class lupwod extends javax.swing.JPanel {

    /**
     * Creates new form pesan
     */
    public lupwod() {
        initComponents();
        setOpaque(false);
        txtnik.setRequestFocusEnabled(true);
        txtpasswordbaru.setEditable(false);
        btnsimpan.setEnabled(false);
    }

    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fill(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 15, 15));
        g2.dispose();
        super.paintComponent(grphcs);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnsimpan = new Swing.btnroundkotak();
        jButton1 = new javax.swing.JButton();
        txtpasswordbaru = new javax.swing.JTextField();
        btnverifikasi = new Swing.btnfllrounded();
        txtusername = new javax.swing.JTextField();
        txtnik = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsimpan.setBackground(new java.awt.Color(62, 181, 84));
        btnsimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnsimpan.setText("Simpan");
        btnsimpan.setFont(new java.awt.Font("Futura Md BT", 1, 20)); // NOI18N
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 130, 40));

        jButton1.setBackground(new java.awt.Color(62, 181, 84));
        jButton1.setFont(new java.awt.Font("Futura Md BT", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(62, 181, 84));
        jButton1.setText("Batal");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, -1, -1));

        txtpasswordbaru.setBackground(new java.awt.Color(240, 240, 240));
        txtpasswordbaru.setFont(new java.awt.Font("Futura Md BT", 1, 16)); // NOI18N
        txtpasswordbaru.setBorder(null);
        txtpasswordbaru.setOpaque(false);
        add(txtpasswordbaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 426, 230, 30));

        btnverifikasi.setBackground(new java.awt.Color(62, 181, 84));
        btnverifikasi.setForeground(new java.awt.Color(255, 255, 255));
        btnverifikasi.setText("✓");
        btnverifikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverifikasiActionPerformed(evt);
            }
        });
        add(btnverifikasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 355, 30, 30));

        txtusername.setBackground(new java.awt.Color(240, 240, 240));
        txtusername.setFont(new java.awt.Font("Futura Md BT", 1, 16)); // NOI18N
        txtusername.setBorder(null);
        txtusername.setOpaque(false);
        add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 354, 230, 30));

        txtnik.setBackground(new java.awt.Color(240, 240, 240));
        txtnik.setFont(new java.awt.Font("Futura Md BT", 1, 16)); // NOI18N
        txtnik.setBorder(null);
        txtnik.setOpaque(false);
        add(txtnik, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 286, 230, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Komponen/lupwod.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Cursor handCursor = new Cursor(Cursor.HAND_CURSOR);
        jButton1.setCursor(handCursor);
        GlassPanePopup.closePopupLast();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        Cursor handCursor = new Cursor(Cursor.HAND_CURSOR);
        btnsimpan.setCursor(handCursor);
        try {
                String sql = "update akun set password = '"+txtpasswordbaru.getText()+"' where nik = '"+txtnik.getText()+"'";
                java.sql.Connection conn=(Connection)konek.configDBek();
                java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                pst.execute();
                GlassPanePopup.showPopup(new luppas_oke());
        } catch (Exception e) {
            System.out.println("gagal diubah");
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnverifikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverifikasiActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "SELECT * FROM akun where username = '"+txtusername.getText()+"' ";
            java.sql.Connection conn=(Connection)konek.configDBek();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            if (rs.next()){
                if(txtnik.getText().equals(rs.getString("nik")) && txtusername.getText().equals(rs.getString("username"))){
                    GlassPanePopup.showPopup(new luppas_true());
                    
                    txtnik.setEditable(false);
                    txtusername.setEditable(false);
                    txtpasswordbaru.setEditable(true);
                    txtpasswordbaru.requestFocus();
                    btnsimpan.setEnabled(true);
                    btnverifikasi.setEnabled(false);
                }
            }else{
                GlassPanePopup.showPopup(new luppas_false());
                txtusername.setText("");
                txtnik.setText("");
                txtnik.requestFocus();
            }
        } catch (Exception e) {
            System.out.println("gagal di konformasi");
        }
    }//GEN-LAST:event_btnverifikasiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Swing.btnroundkotak btnsimpan;
    private Swing.btnfllrounded btnverifikasi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtnik;
    private javax.swing.JTextField txtpasswordbaru;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
